config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  root to: 'passwords#index'
  resources :passwords
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/password.rb
class Password < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def index
    @Passwords = Password.all
  end

  def show
    @password = Password.find(params[:id])
  end

  def new
    @password = Password.new
  end

  def edit
  end

  def create
    password = Password.new(password_params)
    password.save!
    redirect_to passwords_url, notice: "「#{password.name}」を登録しました。"
  end

  private

  def password_params
    params.require(:password).permit(:name, :user_id, :mail, :password_digest, :memo)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def show
  end

  def new
    @password = Password.new
  end

  def edit
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>

app/views/admin/users/new.html.erb
<h1 class ="title">PassWordrobe</h1>
    <nav class="nav justify-content-end">
        <%=link_to "一覧", passwords_path, class: "nav-link" %>
    </nav>
    <div class="container">
        <%= form_with model: [:admin, @user], local: true do |form|%>
            <div class="form-group">
                <%= form.label :name, "名前"%>
                <%= form.text_field :name, class: "form-control", id: "user_name"%>
            </div>
            <div class="form-group">
                <%= form.label :mail, "メールアドレス"%>
                <%= form.text_field :mail, class: "form-control", id: "user_mail"%>
            </div>
            <div class="form-check">
                <%= form.label :admin, "管理者権限", class: "form-check-label"%>
                <%= form.check_box :admin, class: "form-check-input", id: "user_password_admin"%>
            </div>
            <div class="form-group">
                <%= form.label :password_digest, "パスワード"%>
                <%= form.password_field :password_digest, class: "form-control", id: "user_password_digest"%>
            </div>
            <div class="form-group">
                <%= form.label :password_confirmation, "パスワード(確認用)"%>
                <%= form.password_field :password_confirmation, class: "form-control", id: "user_password_confirmation"%>
            </div>
            <div class="submitbutton">
                <%= form.submit "登録する" , class: "btn btn-primary"%>
            </div>
        <% end %>
    </div>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasswordManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <% if flash[:notice].present? %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>  
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1 class ="title">PassWordrobe</h1>
    <div class="area1">
        <div class="area2">
            <%= text_field_tag "searchtext","" %>
            <%=button_to "検索", "", class: "btn btn-primary" %>
        </div>
        <div class="area2">
            <%=link_to "＋新規登録", new_task_path, class: "btn btn-success" %>
            <%=button_to "削除", "", class: "btn btn-danger" %>
        </div>
    </div>